[env:cardputer]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = m5stack/M5Cardputer
build_flags =
    -DLGFX_USE_EFONT=1
    -DBOARD_HAS_PSRAM=0
monitor_speed = 115200
board_build.flash_mode = qio
board_build.flash_size = 8MB
board_build.partitions = huge_app.csv
